(part "NCP51460SN33T1G"
    (packageRef "SOT96P237X111-3N")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INPUT))
        (port "2" (symbPinId 2) (portName "VOUT") (portType OUTPUT))
        (port "3" (symbPinId 3) (portName "GND") (portType GROUND))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "863-NCP51460SN33T1G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/NCP51460SN33T1G?qs=yYCK2ysgWqmLP%2FSKTB%252Bdng%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "NCP51460SN33T1G")
    (property "Description" "Operating Input Voltage VIN 4.2 V to 28 V; Output Current Capability of 0 to 20 mA; Output Voltage Temperature Coefficient of 18 ppm/C; Output Voltage Accuracy 1 %, for 0 C TA 100 C ; High PSRR of 68 dB at 1 kHz; Stable Without Output Capacitor; Low Quiescent Current of 140 A; Low Output Noise of 18 VRMS; Output Voltage Option: 3.3V")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/NCP51460-D.PDF")
    (property "symbolName1" "NCP51460SN33T1G")
)
