(part "SFH6916"
    (packageRef "SOIC127P700X230-16N")
    (interface
        (port "1" (symbPinId 1) (portName "A_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "K_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "A_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "K_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "A_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "K_3") (portType INOUT))
        (port "7" (symbPinId 7) (portName "A_4") (portType INOUT))
        (port "8" (symbPinId 8) (portName "K_4") (portType INOUT))
        (port "9" (symbPinId 9) (portName "E_1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "C_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "E_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "C_2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "E_3") (portType INOUT))
        (port "14" (symbPinId 14) (portName "C_3") (portType INOUT))
        (port "15" (symbPinId 15) (portName "E_4") (portType INOUT))
        (port "16" (symbPinId 16) (portName "C_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "782-SFH6916")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Semiconductors/SFH6916?qs=xCMk%252BIHWTZMHOsdqeojy6Q%3D%3D")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SFH6916")
    (property "Description" "Optocoupler DC-IN 4-CH Trans DC-OUT")
    (property "Datasheet_Link" "http://www.vishay.com/docs/83687/sfh6916.pdf")
    (property "symbolName1" "SFH6916")
)
