(part "CONBNC001"
    (packageRef "CONBNC001")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "712-CONBNC001")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-Linx-Technologies/CONBNC001?qs=doiCPypUmgHczHAGaJs8Lg%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "CONBNC001")
    (property "Description" "Body Features: Body Material Brass | Body Plating Material Nickel | Configuration Features: Number of Coaxial Contacts 1 | Number of Positions 1 | Electrical Characteristics: Impedance 50 OHM | Mechanical Attachment: Connector Mounting Type Board Mount | RF Connector Coupling Mechanism Bayonet | Operation/Application: Operating Frequency 3 GHZ | Circuit Application Signal | Other: Dielectric Material Polytetrafluoroethylene (PTFE) | Product Type Features: RF Connector Style Jack | Connector & Contact Termin")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=CONBNC001&DocType=Data%20Sheet&DocLang=English&PartCntxt=CONBNC001&DocFormat=pdf")
    (property "symbolName1" "CONBNC001")
)
