(part "NCP1117LPST33T3G"
    (packageRef "SOT230P700X180-4N")
    (interface
        (port "1" (symbPinId 1) (portName "ADJUST/GROUND") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OUTPUT_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "INPUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "OUTPUT_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "863-NCP1117LPST33T3G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/NCP1117LPST33T3G?qs=kbSN2QblFfKG9A4Foh4YYg%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "NCP1117LPST33T3G")
    (property "Description" "Output Current in Excess of 1.0 A")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/NCP1117LP-D.PDF")
    (property "symbolName1" "NCP1117LPST33T3G")
)
