PULSONIX_LIBRARY_ASCII "SamacSys ECAD Model"
//19108179/122786/2.50/5/2/Connector

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "c240_h160"
		(holeDiam 1.6)
		(padShape (layerNumRef 1) (padShapeType Ellipse)  (shapeWidth 2.400) (shapeHeight 2.400))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 2.400) (shapeHeight 2.400))
	)
	(padStyleDef "s180_h120"
		(holeDiam 1.2)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 1.800) (shapeHeight 1.800))
		(padShape (layerNumRef 16) (padShapeType Rect)  (shapeWidth 1.800) (shapeHeight 1.800))
	)
	(textStyleDef "Normal"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 1.27)
			(strokeWidth 0.127)
		)
	)
	(patternDef "CONBNC001" (originalName "CONBNC001")
		(multiLayer
			(pad (padNum 1) (padStyleRef s180_h120) (pt 0.000, 0.000) (rotation 90))
			(pad (padNum 2) (padStyleRef c240_h160) (pt -3.150, 3.150) (rotation 90))
			(pad (padNum 3) (padStyleRef c240_h160) (pt -3.150, -3.150) (rotation 90))
			(pad (padNum 4) (padStyleRef c240_h160) (pt 3.150, -3.150) (rotation 90))
			(pad (padNum 5) (padStyleRef c240_h160) (pt 3.150, 3.150) (rotation 90))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt 0.000, 0.000) (textStyleRef "Normal") (isVisible True))
		)
		(layerContents (layerNumRef Courtyard_Top)
			(line (pt -6.5 6.5) (pt 6.5 6.5) (width 0.1))
		)
		(layerContents (layerNumRef Courtyard_Top)
			(line (pt 6.5 6.5) (pt 6.5 -6.5) (width 0.1))
		)
		(layerContents (layerNumRef Courtyard_Top)
			(line (pt 6.5 -6.5) (pt -6.5 -6.5) (width 0.1))
		)
		(layerContents (layerNumRef Courtyard_Top)
			(line (pt -6.5 -6.5) (pt -6.5 6.5) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt -5.5 0) (pt -5.5 0) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(arc (pt 0, 0) (radius 5.5) (startAngle 180) (sweepAngle 180.0) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt 5.5 0) (pt 5.5 0) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(arc (pt 0, 0) (radius 5.5) (startAngle .0) (sweepAngle 180.0) (width 0.025))
		)
		(layerContents (layerNumRef 18)
			(line (pt -6 0) (pt -6 0) (width 0.1))
		)
		(layerContents (layerNumRef 18)
			(arc (pt -6.05, 0) (radius 0.05) (startAngle .0) (sweepAngle 180.0) (width 0.1))
		)
		(layerContents (layerNumRef 18)
			(line (pt -6.1 0) (pt -6.1 0) (width 0.1))
		)
		(layerContents (layerNumRef 18)
			(arc (pt -6.05, 0) (radius 0.05) (startAngle 180) (sweepAngle 180.0) (width 0.1))
		)
	)
	(symbolDef "CONBNC001" (originalName "CONBNC001")

		(pin (pinNum 1) (pt 0 mils 0 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -25 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(pin (pinNum 2) (pt 0 mils -100 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -125 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(pin (pinNum 3) (pt 0 mils -200 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -225 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(pin (pinNum 4) (pt 800 mils 0 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 570 mils -25 mils) (rotation 0]) (justify "Right") (textStyleRef "Normal"))
		))
		(pin (pinNum 5) (pt 800 mils -100 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 570 mils -125 mils) (rotation 0]) (justify "Right") (textStyleRef "Normal"))
		))
		(line (pt 200 mils 100 mils) (pt 600 mils 100 mils) (width 6 mils))
		(line (pt 600 mils 100 mils) (pt 600 mils -300 mils) (width 6 mils))
		(line (pt 600 mils -300 mils) (pt 200 mils -300 mils) (width 6 mils))
		(line (pt 200 mils -300 mils) (pt 200 mils 100 mils) (width 6 mils))
		(attr "RefDes" "RefDes" (pt 650 mils 300 mils) (justify Left) (isVisible True) (textStyleRef "Normal"))
		(attr "Type" "Type" (pt 650 mils 200 mils) (justify Left) (isVisible True) (textStyleRef "Normal"))

	)
	(compDef "CONBNC001" (originalName "CONBNC001") (compHeader (numPins 5) (numParts 1) (refDesPrefix J)
		)
		(compPin "1" (pinName "1") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Unknown))
		(compPin "2" (pinName "2") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Unknown))
		(compPin "3" (pinName "3") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Unknown))
		(compPin "4" (pinName "4") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Unknown))
		(compPin "5" (pinName "5") (partNum 1) (symPinNum 5) (gateEq 0) (pinEq 0) (pinType Unknown))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "CONBNC001"))
		(attachedPattern (patternNum 1) (patternName "CONBNC001")
			(numPads 5)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
				(padNum 3) (compPinRef "3")
				(padNum 4) (compPinRef "4")
				(padNum 5) (compPinRef "5")
			)
		)
		(attr "Mouser Part Number" "712-CONBNC001")
		(attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-Linx-Technologies/CONBNC001?qs=doiCPypUmgHczHAGaJs8Lg%3D%3D")
		(attr "Manufacturer_Name" "TE Connectivity")
		(attr "Manufacturer_Part_Number" "CONBNC001")
		(attr "Description" "Body Features: Body Material Brass | Body Plating Material Nickel | Configuration Features: Number of Coaxial Contacts 1 | Number of Positions 1 | Electrical Characteristics: Impedance 50 OHM | Mechanical Attachment: Connector Mounting Type Board Mount | RF Connector Coupling Mechanism Bayonet | Operation/Application: Operating Frequency 3 GHZ | Circuit Application Signal | Other: Dielectric Material Polytetrafluoroethylene (PTFE) | Product Type Features: RF Connector Style Jack | Connector & Contact Termin")
		(attr "<Hyperlink>" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=CONBNC001&DocType=Data%20Sheet&DocLang=English&PartCntxt=CONBNC001&DocFormat=pdf")
		(attr "<Component Height>" "14.9")
		(attr "<STEP Filename>" "CONBNC001.stp")
		(attr "<STEP Offsets>" "X=0;Y=0;Z=14.4")
		(attr "<STEP Rotation>" "X=0;Y=0;Z=0")
	)

)
