(part "SN65C1168EPWR"
    (packageRef "SOP65P640X120-16N")
    (interface
        (port "1" (symbPinId 1) (portName "1B") (portType INOUT))
        (port "2" (symbPinId 2) (portName "1A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "1R") (portType INOUT))
        (port "4" (symbPinId 4) (portName "%RE%") (portType INOUT))
        (port "5" (symbPinId 5) (portName "2R") (portType INOUT))
        (port "6" (symbPinId 6) (portName "2A") (portType INOUT))
        (port "7" (symbPinId 7) (portName "2B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND") (portType INOUT))
        (port "9" (symbPinId 9) (portName "2D") (portType INOUT))
        (port "10" (symbPinId 10) (portName "2Y") (portType INOUT))
        (port "11" (symbPinId 11) (portName "2Z") (portType INOUT))
        (port "12" (symbPinId 12) (portName "DE") (portType INOUT))
        (port "13" (symbPinId 13) (portName "1Z") (portType INOUT))
        (port "14" (symbPinId 14) (portName "1Y") (portType INOUT))
        (port "15" (symbPinId 15) (portName "ID") (portType INOUT))
        (port "16" (symbPinId 16) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-SN65C1168EPWR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/SN65C1168EPWR?qs=qRemG2J%252Bg%2FV5zfprVJi%2FKg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "SN65C1168EPWR")
    (property "Description" "Dual Differential Drivers and Receivers With +/-15-kV IEC ESD Protection")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/sn65c1168e")
    (property "symbolName1" "SN65C1168EPWR")
)
