(part "05085C102KAT2A"
    (packageRef "CAPC1320X76N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "581-05085C102KAT2A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/AVX/05085C102KAT2A?qs=bvr9a6HSd9Vjw0t4sQ1KPQ%3D%3D")
    (property "Manufacturer_Name" "Kyocera AVX")
    (property "Manufacturer_Part_Number" "05085C102KAT2A")
    (property "Description" "Cap Ceramic 0.001uF 50V X7R 10% Wide Terminal SMD 0508 125C Embossed T/R")
    (property "Datasheet_Link" "https://datasheets.kyocera-avx.com/LICC.pdf")
    (property "symbolName1" "05085C102KAT2A")
)
